<script>
  export let assetsPath = './';
  import Cloud1 from '$assets/clouds/Layer 20.png';
  import Cloud2 from '$assets/clouds/Layer 21.png';
  import Cloud3 from '$assets/clouds/Layer 22.png';
  let width = null;
  import { onMount } from 'svelte';
  export let onAiMounted = () => {};
  onMount(() => {
    onAiMounted();
  });
</script>

<div id="g-diagram-box" bind:clientWidth={width}>
  <!-- Artboard: Artboard_84 -->
  {#if width && width >= 0}
    <div id="g-diagram-Artboard_84" class="g-artboard relative" style="">
      <div style="padding: 0 0 85.5528% 0;"></div>
      <div
        id="g-diagram-Artboard_84-img"
        class="g-aiImg"
        alt=""
        style="background-image: url({assetsPath.replace(
          new RegExp('/([^/.]+)$'),
          '/$1/'
        ) || '/'}ai2html/diagram-Artboard_84.webp);"
      ></div>
      <img
        src={Cloud1}
        class="absolute top-0 left-0 w-[8%] animate-cloud-1"
        alt=""
      />
      <img
        src={Cloud2}
        class="absolute top-2 left-10 w-[8%] animate-cloud-2"
        alt=""
      />
      <img
        src={Cloud3}
        class="absolute top-6 left-0 w-[8%] animate-cloud-3"
        alt=""
      />
      <!-- <div
        id="g-ai0-1"
        class="g-Layer_1 g-aiAbs g-aiPointText"
        style="top:9.8522%;margin-top:-7.7px;left:8.6864%;width:93px;"
      >
        <p class="g-pstyle0">Drainage area</p>
      </div> -->
      <div
        id="g-ai0-2"
        class="g-Layer_1 g-aiAbs"
        style="top:22.2277%;right:-1.3684%;width:62.3443%;"
      >
        <p>Water runs through natural channels in the land...</p>
      </div>
      <div
        id="g-ai0-3"
        class="g-Layer_1 g-aiAbs"
        style="top:75.4315%;right:23.9912%;width:55.459%;"
      >
        <p class="g-pstyle1">
          ...towards the lowest points where it is bound to collect
        </p>
      </div>
    </div>
  {/if}
</div>

<!-- End ai2html - 2024-11-13 22:05 -->

<!-- Generated by ai2html v0.100.0 - 2024-11-13 22:05 -->
<!-- ai file: diagram.ai -->
<style>
  #g-diagram-box p {
    font-family: 'Supreme-Regular', sans-serif !important;
    /* font-weight: 600 !important; */
    color: #122210 !important;
    line-height: 1rem !important;
    font-size: 0.8rem !important;
    container-type: inline-size;
  }

  #g-diagram-box,
  #g-diagram-box .g-artboard {
    margin: 0 auto;
  }
  #g-diagram-box p {
    margin: 0;
  }
  #g-diagram-box .g-aiAbs {
    position: absolute;
  }
  #g-diagram-box .g-aiImg {
    position: absolute;
    top: 0;
    display: block;
    width: 100% !important;
    height: 100%;
    background-size: contain;
    background-repeat: no-repeat;
  }

  #g-diagram-Artboard_84 {
    position: relative;
    overflow: hidden;
  }
  #g-diagram-Artboard_84 p {
    font-family: 'Supreme-Regular', sans-serif !important;
    font-weight: 600;
    line-height: 14px;
    opacity: 1;
    letter-spacing: 0em;
    font-size: 12px;
    text-align: left;
    color: rgb(0, 0, 0);
    text-transform: none;
    padding-bottom: 0;
    padding-top: 0;
    mix-blend-mode: normal;
    font-style: normal;
    height: auto;
    position: static;
  }
  #g-diagram-Artboard_84 .g-pstyle1 {
    text-align: left;
  }

  #g-diagram-Artboard_84 {
    position: relative;
    overflow: hidden;
    container-type: inline-size;
  }

  /* Custom CSS */
  @keyframes floatCloud {
    0% {
      transform: translateX(calc(-10cqw + 100%));
      opacity: 1;
    }

    100% {
      transform: translateX(calc(120cqw - 100%));
      opacity: 1;
    }
  }

  .animate-cloud-1 {
    animation: floatCloud 38s linear infinite;
  }

  .animate-cloud-2 {
    animation: floatCloud 42s linear infinite;
  }

  .animate-cloud-3 {
    animation: floatCloud 47s linear infinite;
  }
</style>
